### ISSUE TITLE
reflect: call of reflect.Value.IsNil on zero Value

### ISSUE THREAD

**Issue by poiuty** [anilibria/anilibria#66]
https://github.com/anilibria/anilibria/blob/master/other/stat.go

```
2019/02/27 14:50:04 http: panic serving @: reflect: call of reflect.Value.IsNil on zero Value
goroutine 148594 [running]:
net/http.(*conn).serve.func1(0xc00cca8aa0)
        /usr/local/go/src/net/http/server.go:1769 +0xc9
panic(0x6c79c0, 0xc000d4b080)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
encoding/json.(*encodeState).marshal.func1(0xc003787bc8)
        /usr/local/go/src/encoding/json/encode.go:302 +0x9a
panic(0x6c79c0, 0xc000d4b080)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
reflect.Value.IsNil(...)
        /usr/local/go/src/reflect/value.go:1049
encoding/json.ptrEncoder.encode(0xc00011c7c0, 0xc00eb9e000, 0x0, 0x0, 0x0, 0x100)
        /usr/local/go/src/encoding/json/encode.go:802 +0x1a4
encoding/json.mapEncoder.encode(0xc000126830, 0xc00eb9e000, 0x6c2740, 0xc000090c00, 0x15, 0x6c0100)
        /usr/local/go/src/encoding/json/encode.go:702 +0x352
encoding/json.(*encodeState).reflectValue(0xc00eb9e000, 0x6c2740, 0xc000090c00, 0x15, 0x6e0100)
        /usr/local/go/src/encoding/json/encode.go:334 +0x82
encoding/json.(*encodeState).marshal(0xc00eb9e000, 0x6c2740, 0xc000090c00, 0x100, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:306 +0xee
encoding/json.Marshal(0x6c2740, 0xc000090c00, 0xc003787c48, 0xc003787c78, 0x4aac4a, 0xc006115a80, 0x0)
        /usr/local/go/src/encoding/json/encode.go:160 +0x52
main.webHandler(0x78a7a0, 0xc00723a7e0, 0xc00d3b6d00)
        /home/ws/go/new2.go:103 +0x3d
net/http.HandlerFunc.ServeHTTP(0x737058, 0x78a7a0, 0xc00723a7e0, 0xc00d3b6d00)
        /usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x987640, 0x78a7a0, 0xc00723a7e0, 0xc00d3b6d00)
        /usr/local/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc000098dd0, 0x78a7a0, 0xc00723a7e0, 0xc00d3b6d00)
        /usr/local/go/src/net/http/server.go:2774 +0xab
net/http.(*conn).serve(0xc00cca8aa0, 0x78ad20, 0xc002defc00)
        /usr/local/go/src/net/http/server.go:1878 +0x84c
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2884 +0x2f4

```

**Comment by poiuty** [comment]
Возможно https://github.com/anilibria/anilibria/commit/60ab6a4aaf248b71d28a1fa795a868b3c413fd9e

**Comment by OnlyloveSY** [comment]
Why did it happen? (reflect: call of reflect.Value.IsNil on zero Value on json.Marshal(data) I have this problem with my project

**Comment by hoani** [comment]
The issue is caused by concurrent access to a map.

The fix that @poiuty posted uses a mutex to allow the data to be marshalled without the map changing
